version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: semantic_search
    ports:
      - "5432:5432"

  server:
    build: ./apps/server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/semantic_search

  semantic-tools:
    build: ./apps/semantic-tools
    ports:
      - "8000:8000"
